### ISSUE TITLE
python: can't open file 'inference.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by FaizaaAkhtar** [vinodbukya6/cp-VTryon-plus-Flask-App#1]
Hi, @vinodbukya6 I am having the above issue after running code. I have done all the steps that are mentioned in the github repo.
1. I installed all the required pacakges. 
2. downloaded pretrained model from the given link https://1drv.ms/u/s!Ai8t8GAHdzVUiQA-o3C7cnrfGN6O?e=EaRiFP 
3. Then downloded inference.pth file from link mentioned on the repo https://drive.google.com/uc?id=1eUe18HoH05p0yFUd_sN6GXdTj82aW0m9  and pasted it under checkpoints folder.
4.  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel  downloaded these two files and pasted in respective folder.
5. Pasted both pretrained and inference model in checkpoints folder as shown below.
      
<img width="290" alt="image" src="https://user-images.githubusercontent.com/119648504/205228421-ae0f250b-bf92-43fd-81ae-d0265fc12bac.png">

6. Then after running the app upon posting person and cloth image we are having following issue.
 
<img width="878" alt="image" src="https://user-images.githubusercontent.com/119648504/205220598-74255bd7-0e1e-4016-b9b3-9a9acee943dc.png">

**Comment by vinodbukya6** [comment]
Hi @FaizaaAkhtar 
At line 61: Can you change this
` cmd_parse = "python inference.py --loadmodel checkpoints/inference.pth --img_path " + filename_person + " --output_path img/ --output_name "+ filename_person `
to:
` cmd_parse = "python tryon_utils/inference.py --loadmodel checkpoints/inference.pth --img_path " + filename_person + " --output_path img/ --output_name "+ filename_person `

About Openpose Model please check here: https://github.com/CMU-Perceptual-Computing-Lab/openpose

**Comment by FaizaaAkhtar** [comment]
> 

thanks @vinodbukya6  it resolved the issue. 
Given below is the result.
cloth and person image.
<img width="157" alt="image" src="https://user-images.githubusercontent.com/119648504/205231057-4c378079-d1fd-4eaa-8d67-d72bd03f3b5a.png">

<img width="146" alt="image" src="https://user-images.githubusercontent.com/119648504/205231122-5e7f4cb2-ec1c-4c86-9f54-d8f7d4c7c3c0.png">

after tryOn 

<img width="151" alt="image" src="https://user-images.githubusercontent.com/119648504/205231301-1ebaa1be-4b2c-4aa5-b799-cbcf416805eb.png">

**Comment by vinodbukya6** [comment]
Great!!!
For better results select person images with **Front Pose** and **Hands Not in front of the body**.
Sample Image: 
![019561_0](https://user-images.githubusercontent.com/46157647/205235213-d6a09662-7937-4a2a-b8d0-b9f292bcb887.jpg)
