### ISSUE TITLE
TOM/ GMM are taking very long to produce results.

### ISSUE THREAD

**Issue by khurramkhalil** [vinodbukya6/cp-VTryon-plus-Flask-App#2]
Hi vinodbukya6,
Thank you for the repo.
The issue I am facing is that TOM/GMM take very long to render results. During process, cpu usage is well below 10%.
Is it expected or I have something wrong?
How many seconds it take for a test image to produce results from upload to end? Thanks

**Comment by vinodbukya6** [comment]
Hi @khurramkhalil 
Inference time is Machine dependent.
I have tested on two different Machines: 
1. 16GB RAM - 8CPU Cores: Inference Time is 9-12s
2. 8GB RAM 2CPU Cores: Inference Time is 20-25s

Hope this helps!!!
