### ISSUE TITLE
results are wrong.

### ISSUE THREAD

**Issue by AyushRajgor** [vinodbukya6/cp-VTryon-plus-Flask-App#3]
Here I attached the screenshot of the result. it shows the weird output. Also, the flask didn't show output on the web as you can see in the 404 error.
![image](https://user-images.githubusercontent.com/76404080/212064224-4adc2708-91f4-4575-b8b2-357a24ee3ed2.png)

**Comment by vinodbukya6** [comment]
Hi @ARajgor 
Can you please share input images?

**Comment by AyushRajgor** [comment]
@vinodbukya6 issue is resolved. I just delete the project and clear the cache of pycharm. it works fine.
