### ISSUE TITLE
can't install pytorch=0.4.1 torchvision=0.2.1

### ISSUE THREAD

**Issue by nuubnoob** [vinodbukya6/cp-VTryon-plus-Flask-App#5]
my python version is 3.9 i used conda but still cant install the required versions

**Comment by vinodbukya6** [comment]
Hi @nuubnoob 
What problem are you facing, can you share the issue?

**Comment by nuubnoob** [comment]
![Screenshot (61)~2](https://user-images.githubusercontent.com/74585280/219264126-8146a6e5-c068-4dd7-b97f-026feaf7b782.png)

**Comment by vinodbukya6** [comment]
Did you run this command: `conda install pytorch=0.4.1 torchvision=0.2.1 -c pytorch` ?

**Comment by nuubnoob** [comment]
Yes I did

**Comment by vinodbukya6** [comment]
Please check how to install pytorch and torchvision on **Windows** machine. This repo is works/tested on **Ubuntu** machine.

**Comment by nuubnoob** [comment]
can you tell me the python version used for this repo

**Comment by vinodbukya6** [comment]
Hi @nuubnoob 
Can you test with python 3.6 version.

**Comment by nuubnoob** [comment]
i am testing on 3.7 i downloaded the required packages and all required models but now i am facing below error

![Web capture_18-2-2023_143757_127 0 0 9](https://user-images.githubusercontent.com/74585280/219852064-ae59ca7b-c63d-4b4e-94b7-6afff3f6d1cf.jpeg)
