### ISSUE TITLE
Couldn't load image on the web page (result.html)

### ISSUE THREAD

**Issue by zaryabirfan** [vinodbukya6/cp-VTryon-plus-Flask-App#7]
Hi @vinodbukya6  thank you for your repo it helped me a lot in my work. I am getting an error and unable to figure it out. 
I am running the project and its totally fine but at the result page images are not loading. I tried many thing let me share with you my screenshots. 
1. I selected both person image and cloth image
<img width="326" alt="image" src="https://user-images.githubusercontent.com/126321024/221349035-2d176f64-b02d-4dea-b191-42cee9d5435c.png">
2. here is result page 
<img width="353" alt="image" src="https://user-images.githubusercontent.com/126321024/221349128-c9723ff7-e30c-4c36-af31-1e533cf612c1.png">
3. given below are code images. You can see  result is saved successfully under try_on folder 
 
<img width="932" alt="image" src="https://user-images.githubusercontent.com/126321024/221349208-c487b71a-593a-4b5f-9d32-bfd058caa4fc.png">
4. here's result.html code
<img width="825" alt="image" src="https://user-images.githubusercontent.com/126321024/221349252-5ea440f9-dbe8-4109-9973-8914b69388c3.png">

**Comment by vinodbukya6** [comment]
Hi @zaryabirfan 

Try this result.html code:
![Screenshot from 2023-02-27 18-45-09](https://user-images.githubusercontent.com/46157647/221573740-0ddede72-d0ab-4879-8323-d5d4a9f80fe7.png)

In app.py change return statement
 `       return render_template('result.html', user_image=result_filename)`

Save images in static directory and load. Sample result_filename: "./static/tryon_images/tryon_result.jpg"
